/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/car/Lambo.gltf 
*/

import React from 'react'
import { useCustomization } from '../Contexts/Customization'
import { useGLTF } from '@react-three/drei'
import { useEffect, useRef } from 'react'
import { useFrame, useThree } from '@react-three/fiber'

export function Lambo(props) {
  const { nodes, materials } = useGLTF('./models/car/Lambo.glb')
  const { tires, sideMirrors, carPaintPrimary, carPaintSecondary, sideMirrorPrimary, sideMirrorSecondary } = useCustomization();
  
  const group = useRef();
  useFrame((state, delta) => {
    if (group.current) group.current.rotation.y += delta * 0.1;
  });

  const camera = useThree((state) => state.camera)
  console.log(camera.position);

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_10.geometry} castShadow material={materials.Meshpart11Mtl} >
          <meshStandardMaterial/>
        </mesh>
        <mesh geometry={nodes.Object_12001.geometry} castShadow material={materials.Meshpart1Mtl} >
          <meshStandardMaterial color={[sideMirrorSecondary.color[0] / 255.0,sideMirrorSecondary.color[1] / 255.0 ,sideMirrorSecondary.color[2] / 255.0]}/>
        </mesh>
        <mesh geometry={nodes.Object_15001.geometry} castShadow material={materials.Meshpart2Mtl} >
          <meshStandardMaterial color={[sideMirrorPrimary.color[0] / 255.0,sideMirrorPrimary.color[1] / 255.0 ,sideMirrorPrimary.color[2] / 255.0]}/>
        </mesh>
        <mesh geometry={nodes.Object_18.geometry} castShadow material={materials.Meshpart34Mtl} >
        </mesh>
        <mesh geometry={nodes.Object_2.geometry} castShadow material={materials.Meshpart3Mtl} >
        </mesh>
        <mesh geometry={nodes.Object_24.geometry} castShadow material={materials.ReverseLight1Mtl}>
        </mesh>
        <mesh geometry={nodes.Object_25.geometry} castShadow material={materials.Rr2Mtl} >
        <meshStandardMaterial/>
        </mesh>
        <mesh geometry={nodes.Object_5.geometry} castShadow material={materials.Meshpart59Mtl} >
        <meshStandardMaterial />
        </mesh>
        <mesh geometry={nodes.Object_6.geometry} castShadow material={materials.Meshpart70Mtl} >
        </mesh>
        <mesh geometry={nodes.Object_7.geometry} castShadow material={materials.Meshpart71Mtl} />

        <mesh geometry={nodes.Object_8.geometry} castShadow material={materials.Rr1Mtl} />

        <mesh geometry={nodes.Object_9.geometry} castShadow material={materials.Blinker1Mtl} >
          <meshStandardMaterial/>  
        </mesh>

        <mesh geometry={nodes.Object_18_1.geometry} castShadow material={materials.Meshpart5Mtl} >
            
        </mesh>
        <mesh geometry={nodes.Object_18_2.geometry} castShadow material={materials.Meshpart2Mtl}>
        <meshStandardMaterial metalness={0.8} roughness={0.1} color={[carPaintSecondary.color[0] / 255.0,carPaintSecondary.color[1] / 255.0 ,carPaintSecondary.color[2] / 255.0]}/>
        </mesh>
        <mesh geometry={nodes.Object_20_1.geometry} castShadow material={materials.Meshpart7Mtl} />
        <mesh geometry={nodes.Object_20_2.geometry} visible={tires===1} castShadow material={materials.Meshpart2Mtl}>
        </mesh>
        <mesh geometry={nodes.Object_20_3.geometry} visible={tires===1} castShadow material={materials.Meshpart8Mtl} >
        </mesh>
        <mesh geometry={nodes.Object_20_4.geometry}  visible={tires===1} castShadow material={materials.Meshpart5Mtl} >
        </mesh>
        <mesh geometry={nodes.Object_2_1.geometry} castShadow material={materials.Meshpart58Mtl} >
        </mesh>
        <mesh geometry={nodes.Object_2_2.geometry}  castShadow material={materials.Meshpart1Mtl} >
          <meshStandardMaterial metalness={0.8} roughness={0.4} color={[carPaintPrimary.color[0] / 255.0,carPaintPrimary.color[1] / 255.0 ,carPaintPrimary.color[2] / 255.0]}/>  
        </mesh>
        <mesh geometry={nodes.Object_2_3.geometry} castShadow material={materials.Meshpart13Mtl} />
        <mesh geometry={nodes.Object_2_4.geometry} castShadow material={materials.Meshpart31Mtl} />
        <mesh geometry={nodes.Object_2_5.geometry} castShadow material={materials.Meshpart52Mtl} />
        <mesh geometry={nodes.Object_2_6.geometry} castShadow material={materials.Meshpart56Mtl} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.046}>
        <group position={[0, 0, 1.242]} scale={3.49}>
          <mesh geometry={nodes.Object_4001.geometry} castShadow visible={tires===2} material={materials['wheels.001']} />
          <mesh geometry={nodes.Object_4001_1.geometry} castShadow visible={tires===2} material={materials['PGNI_Breaks.001']} />
        </group>
      </group>
      <mesh geometry={nodes.Wheel_FL_RIMSPORT_03_2_0002.geometry} castShadow visible={tires===0} material={materials['RIMSPORT_03_2.001']} position={[1.186, 2.727, -1.291]} rotation={[0, 1.571, 0]} scale={[-0.028, -0.028, -0.546]} />
    </group>
  )
}

useGLTF.preload('./models/car/Lambo.glb')
