/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/car/lambo_new.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Lambo(props) {
  const { nodes, materials } = useGLTF('/models/car/lambo_new.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh castShadow geometry={nodes.Object_10.geometry} material={materials.Meshpart11Mtl} />
        <mesh castShadow geometry={nodes.Object_11.geometry} material={materials.Meshpart13Mtl} />
        <mesh castShadow geometry={nodes.Object_12.geometry} material={materials.Meshpart1Mtl} />
        <mesh castShadow geometry={nodes.Object_13.geometry} material={materials.Meshpart1Mtl} />
        <mesh castShadow geometry={nodes.Object_14.geometry} material={materials.Meshpart2Mtl} />
        <mesh castShadow geometry={nodes.Object_15.geometry} material={materials.Meshpart2Mtl} />
        <mesh castShadow geometry={nodes.Object_16.geometry} material={materials.Meshpart2Mtl} />
        <mesh castShadow geometry={nodes.Object_17.geometry} material={materials.Meshpart31Mtl} />
        <mesh castShadow geometry={nodes.Object_18.geometry} material={materials.Meshpart34Mtl} />
        <mesh castShadow geometry={nodes.Object_19.geometry} material={materials.Meshpart52Mtl} />
        <mesh castShadow geometry={nodes.Object_2.geometry} material={materials.Meshpart3Mtl} />
        <mesh castShadow geometry={nodes.Object_20.geometry} material={materials.Meshpart5Mtl} />
        <mesh castShadow geometry={nodes.Object_21.geometry} material={materials.Meshpart5Mtl} />
        <mesh castShadow geometry={nodes.Object_22.geometry} material={materials.Meshpart7Mtl} />
        <mesh castShadow geometry={nodes.Object_23.geometry} material={materials.Meshpart8Mtl} />
        <mesh castShadow geometry={nodes.Object_24.geometry} material={materials.ReverseLight1Mtl} />
        <mesh castShadow geometry={nodes.Object_25.geometry} material={materials.Rr2Mtl} />
        <mesh castShadow geometry={nodes.Object_3.geometry} material={materials.Meshpart56Mtl} />
        <mesh castShadow geometry={nodes.Object_4.geometry} material={materials.Meshpart58Mtl} />
        <mesh castShadow geometry={nodes.Object_5.geometry} material={materials.Meshpart59Mtl} />
        <mesh castShadow geometry={nodes.Object_6.geometry} material={materials.Meshpart70Mtl} />
        <mesh castShadow geometry={nodes.Object_7.geometry} material={materials.Meshpart71Mtl} />
        <mesh castShadow geometry={nodes.Object_8.geometry} material={materials.Rr1Mtl} />
        <mesh castShadow geometry={nodes.Object_9.geometry} material={materials.Blinker1Mtl} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/car/lambo_new.glb')
